name: CD/CD-client
on:
  push:
    branches:
      - feature/fix-ci-cd
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: build image
        env:
          VITE_EMQX_DOMAIN: ${{secrets.VITE_EMQX_DOMAIN}}
          VITE_API_DOMAIN: ${{secrets.VITE_API_DOMAIN}}
          VITE_EMQX_PROTOCAL: ${{secrets.VITE_EMQX_PROTOCAL}}
          VITE_EMQX_HOST: ${{secrets.VITE_EMQX_HOST}}
        run: docker build -t sekkarin/warering-client .
      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: push image to docker hub
        run: docker push sekkarin/warering-client
      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.5.1
        with:
          token: ${{secrets.DIGITALOCEAN_TOKEN}}
      - name: rollout client deployment
        run: doctl kubernetes cluster kubeconfig save k8s-1-30-1-do-0-sgp1-1718101032317 && kubectl rollout restart deployment client-depl
    
